import { Geist, Geist_Mono, Edu_SA_Beginner } from "next/font/google";

import "./globals.css";
import Navbar from "./Header/page";
import { Toaster } from "react-hot-toast";
const edusa = Edu_SA_Beginner({
  variable: "--font-edusa-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar/>
        <Toaster
  position="top-center"
  reverseOrder={false}
/>
        {children}</body>
    </html>
  );
}
